services:
  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    ports:
      - "9042:9042"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - CASSANDRA_HOST=cassandra
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "3000:80"  # React dev on 3000, but nginx uses 80
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
